language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
scala:
  - "2.12.6"
jdk:
  - openjdk11
script:
  - sbt ++${TRAVIS_SCALA_VERSION} scalafmtCheck
  - sbt ++${TRAVIS_SCALA_VERSION} test
